/**
 * Workbench export helpers.
 *
 * Pure functions extracted verbatim from ``Workbench.jsx``. Each one
 * builds a file in memory and triggers a download via a temporary
 * anchor click — no React state involved, which makes them easy to
 * test and reason about independently of the page.
 */

import formatTime from '../../utils/formatTime'
import { escapeHtml as esc } from '../../utils/escapeHtml'
import { estimateCost } from '../../utils/pricing'
import { ACTION_LABEL_MAP } from './constants'

function _triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

/** Download the full session (task + steps + logs + summary) as JSON. */
export function exportSessionJSON({ task, model, provider, fetchedModels, steps, logs }) {
  const modelMeta = fetchedModels.find(m => m.model_id === model)
  const cost = estimateCost(model, steps.length)
  const data = {
    task, model, provider,
    modelDisplayName: modelMeta?.display_name || model,
    steps: steps.map(s => ({
      step_number: s.step_number,
      action: s.action,
      actionLabel: ACTION_LABEL_MAP[s.action?.action] || s.action?.action || 'Unknown',
      error: s.error,
      timestamp: s.timestamp,
    })),
    logs: logs.map(l => ({ timestamp: l.timestamp, level: l.level, message: l.message })),
    summary: {
      totalSteps: steps.length,
      estimatedCost: cost ? `~$${cost.cost.toFixed(4)}` : null,
      costNote: cost?.note || null,
    },
    exportedAt: new Date().toISOString(),
  }
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
  _triggerDownload(blob, `cua_session_${new Date().toISOString().replace(/[:.]/g, '-')}.json`)
}

/** Download a self-contained styled HTML session report. */
export function exportSessionHTML({ task, model, provider, fetchedModels, steps, logs }) {
  const modelMeta = fetchedModels.find(m => m.model_id === model)
  const displayModel = modelMeta?.display_name || model
  const cost = estimateCost(model, steps.length)
  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>CUA Session Report</title>
<style>body{font-family:system-ui;max-width:800px;margin:40px auto;padding:0 20px;color:#333}h1{color:#6c63ff}.summary{background:#f5f5ff;border:1px solid #e0e0ff;border-radius:8px;padding:16px;margin:16px 0}.summary p{margin:4px 0}.summary strong{display:inline-block;min-width:120px}table{width:100%;border-collapse:collapse;margin:16px 0}th,td{padding:8px;border:1px solid #ddd;text-align:left}th{background:#f5f5f5}.step{margin:8px 0;padding:10px 12px;background:#f9f9f9;border-radius:6px;border-left:3px solid #6c63ff}.step-label{font-weight:600;color:#333}.reasoning{color:#666;font-style:italic;margin-top:4px}.error{color:#dc3545}h2{margin-top:32px;border-bottom:1px solid #eee;padding-bottom:8px}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #eee;font-size:12px;color:#999}</style></head><body>
<h1>Session Report</h1>
<div class="summary">
<p><strong>Task:</strong> ${esc(task)}</p>
<p><strong>Model:</strong> ${esc(displayModel)} (${esc(provider)})</p>
<p><strong>Steps:</strong> ${steps.length}</p>
${cost ? `<p><strong>Estimated Cost:</strong> ~$${cost.cost.toFixed(4)} <span style="color:#999;font-size:12px">(${esc(cost.note)})</span></p>` : ''}
<p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
</div>
<h2>Timeline</h2>
${steps.map(s => {
  const label = ACTION_LABEL_MAP[s.action?.action] || s.action?.action || 'Unknown'
  return `<div class="step"><span class="step-label">#${s.step_number} &mdash; ${esc(label)}</span>${s.action?.reasoning ? `<div class="reasoning">${esc(s.action.reasoning)}</div>` : ''}${s.error ? `<div class="error">${esc(s.error)}</div>` : ''}</div>`
}).join('')}
<h2>Logs</h2>
<table><tr><th>Time</th><th>Level</th><th>Message</th></tr>
${logs.map(l => `<tr><td>${formatTime(l.timestamp)}</td><td>${esc(l.level)}</td><td>${esc(l.message)}</td></tr>`).join('')}
</table>
<div class="footer">Generated by CUA — Computer Using Agent</div>
</body></html>`
  const blob = new Blob([html], { type: 'text/html' })
  _triggerDownload(blob, `cua_session_${new Date().toISOString().replace(/[:.]/g, '-')}.html`)
}

/** Download the current logs as a timestamped plain-text file. */
export function downloadLogsTxt(logs) {
  if (logs.length === 0) return
  const now = new Date()
  const pad = (n, w = 2) => String(n).padStart(w, '0')
  const filename = `CUA_logs_${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}_${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}.txt`
  const lines = logs.map(log => {
    const ts = formatTime(log.timestamp)
    return `[${ts}] [${(log.level || '').toUpperCase()}] ${log.message}`
  })
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  _triggerDownload(blob, filename)
}

/** Format logs into a plain-text block suitable for clipboard pasting. */
export function formatLogsForClipboard(logs) {
  return logs.map(log => {
    const ts = formatTime(log.timestamp)
    return `[${ts}] [${(log.level || '').toUpperCase()}] ${log.message}`
  }).join('\n')
}

/** Format the step timeline into a plain-text block suitable for clipboard pasting. */
export function formatTimelineForClipboard(steps) {
  return steps.map(step => {
    const ts = formatTime(step.timestamp)
    const action = ACTION_LABEL_MAP[step.action?.action] || step.action?.action || 'Unknown'
    const parts = [`#${step.step_number}`, `[${ts}]`, action]
    if (step.action?.target) parts.push(`→ ${step.action.target}`)
    if (step.action?.text && step.action.action !== 'done') parts.push(`"${step.action.text}"`)
    if (step.action?.coordinates) parts.push(`@[${step.action.coordinates.join(', ')}]`)
    const head = parts.join(' ')
    const detail = []
    if (step.action?.reasoning) detail.push(`  ${step.action.reasoning}`)
    if (step.error) detail.push(`  Error: ${step.error}`)
    return detail.length ? `${head}\n${detail.join('\n')}` : head
  }).join('\n')
}
